const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={console,window:{},localStorage:{getItem(){return null},setItem(){},removeItem(){}},TEAMS:{al_nassr:{name:'Al Nassr',country:'Arabia Saudita',sport:'futbol'},pumas:{name:'Pumas UNAM',country:'México',sport:'futbol'}},STORAGE_SCHEMA_VERSION:3,DEFAULT_WEEK_DEFS:[]};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('assets/js/core/state.js','utf8'),ctx);
let d=ctx.normalizedMatch({team:'al_nassr',venueSide:'home',rival:'Al Fateh SC',rivalCountry:'Arabia Saudita',originLocal:'Arabia Saudita',originVisit:'Arabia Saudita',internacional:false,gf:3,gc:0},null);
assert.strictEqual(d.originLocal,'—'); assert.strictEqual(d.originVisit,'—');
let i=ctx.normalizedMatch({team:'pumas',venueSide:'away',rival:'Charlotte FC',rivalCountry:'Estados Unidos',originLocal:'—',originVisit:'—',internacional:true,gf:0,gc:3},null);
assert.strictEqual(i.originLocal,'Estados Unidos'); assert.strictEqual(i.originVisit,'México');
const dash=fs.readFileSync('assets/js/pages/dashboard.js','utf8');
assert(dash.includes("m.internacional===true?`<small>${escapeHtml(origin||'—')}</small>`:''"));
console.log('PASS origins render only for explicitly international matches');
